# Generated by Django 4.1.13 on 2026-01-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('durationweeks', models.PositiveIntegerField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.stream')),
            ],
            options={
                'db_table': 'tbl_course',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchcode', models.CharField(max_length=50, unique=True)),
                ('batchname', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
            ],
            options={
                'db_table': 'tbl_batch',
            },
        ),
    ]
