# Generated by Django 4.1.13 on 2026-01-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_course_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.TextField()),
                ('experienceyear', models.PositiveIntegerField()),
                ('bio', models.FileField(blank=True, null=True, upload_to='teacherbio/')),
                ('profilepic', models.FileField(blank=True, null=True, upload_to='teacherpic/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.stream')),
            ],
            options={
                'db_table': 'tbl_teacher',
            },
        ),
    ]
