# Generated by Django 4.1.13 on 2026-01-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_tbl_student_created_at_and_more'),
        ('adminapp', '0003_tbl_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teacher',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_login'),
            preserve_default=False,
        ),
    ]
