# Generated by Django 4.1.13 on 2026-01-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_teacherbatch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbl_teacherbatch',
            unique_together={('teacher', 'batch')},
        ),
        migrations.AlterModelTable(
            name='tbl_teacherbatch',
            table='tbl_teacherbatch',
        ),
    ]
