# Generated by Django 4.1.13 on 2026-01-30 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_tbl_teacherbatch_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalscore', models.IntegerField()),
                ('examcode', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('answerstatus', models.BooleanField(default='false')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_question')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.exam')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_question')),
            ],
        ),
    ]
