# Generated by Django 4.1.13 on 2026-02-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_exam_tbl_question_tbl_option_tbl_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='courseimage/'),
        ),
        migrations.AddField(
            model_name='course',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
