# Generated by Django 4.1.13 on 2026-02-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_course_image_course_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
