# Generated by Django 4.1.13 on 2026-02-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_tbl_doubt_lesson_id'),
        ('adminapp', '0009_batch_startdate_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student_examresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score_obtained', models.IntegerField()),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.exam')),
                ('student_enrol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.tbl_student_enrolment')),
            ],
        ),
    ]
