# Generated by Django 4.1.13 on 2026-01-09 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='studentpic/'),
        ),
    ]
