# Generated by Django 4.1.13 on 2026-02-17 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0009_batch_startdate_batch_status'),
        ('homeapp', '0002_alter_tbl_student_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student_enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(default='active', max_length=100)),
                ('enrollment_date', models.DateField(verbose_name=datetime.date.today)),
                ('is_active_student', models.CharField(default='yes', max_length=100)),
                ('enrolled_batchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField(verbose_name=datetime.date.today)),
                ('payment_mode', models.CharField(default='card', max_length=100)),
                ('paymentstatus', models.CharField(default='pending', max_length=100)),
                ('student_enrol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.tbl_student_enrolment')),
            ],
        ),
    ]
