# Generated by Django 4.1.13 on 2026-02-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
