# Generated by Django 4.1.13 on 2026-02-17 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_delete_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(default='card', max_length=100)),
                ('paymentstatus', models.CharField(default='pending', max_length=100)),
                ('student_enrol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.tbl_student_enrolment')),
            ],
        ),
    ]
