# Generated by Django 4.1.13 on 2026-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
