# Generated by Django 4.1.13 on 2026-02-17 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_tbl_assignment'),
        ('homeapp', '0002_alter_tbl_student_created_at_and_more'),
        ('studentapp', '0004_tbl_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignmentstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitteddate', models.DateTimeField(default=datetime.date.today)),
                ('assignmentuploaded', models.FileField(upload_to='assignment_submission/')),
                ('assigned_marks', models.IntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, to='teacherapp.tbl_assignment')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_student')),
            ],
            options={
                'db_table': 'tbl_assignmentstudent',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
