# Generated by Django 4.1.13 on 2026-02-20 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_tbl_assignmentstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_submitted', models.DateTimeField(default=datetime.date.today)),
                ('answer', models.CharField(max_length=200)),
                ('answer_submitted', models.DateTimeField(default=datetime.date.today)),
                ('student_enrolment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.tbl_student_enrolment')),
            ],
        ),
    ]
