# Generated by Django 4.1.13 on 2026-02-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_tbl_assignment_assignmentupload_and_more'),
        ('studentapp', '0006_tbl_doubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doubt',
            name='lesson_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.tbl_lessons'),
        ),
    ]
