# Generated by Django 4.1.13 on 2026-03-04 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_tbl_student_created_at_and_more'),
        ('adminapp', '0010_tbl_student_examresult'),
        ('studentapp', '0007_tbl_doubt_lesson_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_course_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_student')),
            ],
            options={
                'db_table': 'tbl_course_review',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
