# Generated by Django 4.1.13 on 2026-01-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0006_alter_tbl_teacherbatch_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulenumber', models.IntegerField()),
                ('moduletitle', models.CharField(max_length=100)),
                ('lessontitle', models.CharField(max_length=100)),
                ('pdfnotes', models.FileField(blank=True, null=True, upload_to='pdfnotes/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch')),
            ],
        ),
    ]
