# Generated by Django 4.1.13 on 2026-01-24 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_tbl_teacherbatch_unique_together_and_more'),
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaddate', models.DateField(default=datetime.date.today)),
                ('duedate', models.DateField()),
                ('totalmarks', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch')),
            ],
        ),
    ]
