# Generated by Django 4.1.13 on 2026-02-20 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_tbl_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_assignment',
            name='assignmentupload',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='tbl_assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterModelTable(
            name='tbl_assignment',
            table='tbl_assignment',
        ),
    ]
