# Generated by Django 4.1.13 on 2026-03-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_tbl_doubt_lesson_id'),
        ('teacherapp', '0003_tbl_assignment_assignmentupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_mark', models.IntegerField()),
                ('student_enrolment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.tbl_student_enrolment')),
            ],
            options={
                'db_table': 'tbl_final',
                'unique_together': {('student_enrolment_id',)},
            },
        ),
    ]
